<?php

namespace Database\Factories;

use App\Models\FiscalDocument;
use App\Models\Order;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class FiscalDocumentFactory extends Factory
{
    protected $model = FiscalDocument::class;

    public function definition()
    {
        $documentTypes = ['FR', 'FT', 'FS', 'NC', 'ND', 'RC', 'FP', 'GR'];
        $paymentMethods = ['cash', 'transfer', 'card', 'multicaixa'];
        $statuses = ['draft', 'issued', 'cancelled'];
        $paymentStatuses = ['pending', 'paid', 'partial', 'overdue'];

        $subtotal = $this->faker->randomFloat(2, 1000, 50000);
        $tax = $subtotal * 0.14; // IVA 14%
        $discount = 0;
        $total = $subtotal + $tax - $discount;

        return [
            'document_type' => $this->faker->randomElement($documentTypes),
            'document_number' => null, // Will be generated by observer
            'serie' => 'A',
            'year' => date('Y'),
            'status' => $this->faker->randomElement($statuses),
            
            // Customer info
            'customer_name' => $this->faker->company(),
            'customer_nif' => $this->faker->numerify('#########'),
            'customer_email' => $this->faker->companyEmail(),
            'customer_phone' => $this->faker->phoneNumber(),
            'customer_address' => $this->faker->address(),
            
            // Dates
            'issue_date' => $this->faker->dateTimeBetween('-30 days', 'now'),
            'due_date' => $this->faker->optional()->dateTimeBetween('now', '+30 days'),
            
            // Amounts
            'subtotal' => $subtotal,
            'discount' => $discount,
            'tax' => $tax,
            'total' => $total,
            
            // Payment
            'payment_method' => $this->faker->randomElement($paymentMethods),
            'payment_status' => $this->faker->randomElement($paymentStatuses),
            'payment_date' => $this->faker->optional()->dateTimeBetween('-30 days', 'now'),
            'payment_reference' => $this->faker->optional()->numerify('REF-######'),
            
            // Relations
            'order_id' => null,
            'user_id' => User::inRandomOrder()->first()->id ?? null,
            'related_document_id' => null,
            
            // Notes
            'notes' => $this->faker->optional()->sentence(),
            
            // AGT fields (will be filled when integrating with AGT)
            'agt_hash' => null,
            'agt_signature' => null,
            'agt_qrcode' => null,
            'agt_atcud' => null,
            'previous_hash' => null,
        ];
    }

    /**
     * Indicate that the document is a draft
     */
    public function draft()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'draft',
                'document_number' => null,
            ];
        });
    }

    /**
     * Indicate that the document is issued
     */
    public function issued()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'issued',
            ];
        });
    }

    /**
     * Indicate that the document is cancelled
     */
    public function cancelled()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'cancelled',
                'cancellation_reason' => $this->faker->sentence(),
            ];
        });
    }

    /**
     * Indicate that the document is paid
     */
    public function paid()
    {
        return $this->state(function (array $attributes) {
            return [
                'payment_status' => 'paid',
                'payment_date' => now(),
            ];
        });
    }

    /**
     * Create a Fatura Recibo (FR)
     */
    public function faturaRecibo()
    {
        return $this->state(function (array $attributes) {
            return [
                'document_type' => 'FR',
            ];
        });
    }

    /**
     * Create a Fatura Simplificada (FS)
     */
    public function faturaSimplificada()
    {
        return $this->state(function (array $attributes) {
            $subtotal = $this->faker->randomFloat(2, 1000, 40000); // Máx 50k com IVA
            $tax = $subtotal * 0.14;
            
            return [
                'document_type' => 'FS',
                'subtotal' => $subtotal,
                'tax' => $tax,
                'total' => $subtotal + $tax,
            ];
        });
    }

    /**
     * Create a Nota de Crédito (NC)
     */
    public function notaCredito()
    {
        return $this->state(function (array $attributes) {
            return [
                'document_type' => 'NC',
                'notes' => 'Devolução de mercadoria',
            ];
        });
    }
}
